#!/bin/bash

set -euo pipefail
COLOR_CONDITIONAL=${COLOR_CONDITIONAL%;}
for SINGLE_PATH in "${@:-.}"; do
  find ${SINGLE_PATH} -maxdepth 1 -type d -not -path "${SINGLE_PATH}" -not -path "${SINGLE_PATH}/\.*" |
    xargs -L 1 bash -euo pipefail -c "[[ ! -d \"\${0}/.git\" ]] && exit 0;
      cd \"\${0}\";
      pwd | awk -v B=$( tput smso ) -v N=$( tput rmso ) '{print B\$0N;}';
      OUTPUT=\$( ${GIT_CMD:?Missing string specifying which \`git\' cmd to run} 2>&1; exit 0; );
      echo \"\${OUTPUT}\" | perl -pe \"s/\$( { ${COLOR_CONDITIONAL:-true}; } && echo \"\" || echo '\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]' )//g\" | awk '{ print \"\t\"\$0;}';"
done
