#!/bin/bash

set -euo pipefail
find ${1:-.} -maxdepth 1 -type d -not -path "${1:-.}" -not -path "${1:-.}/\.*" |
  xargs -L 1 bash -euo pipefail -c "[[ ! -d \"\${0}/.git\" ]] && exit 0;
    cd \"\${0}\";
    pwd | awk -v B=$( tput smso ) -v N=$( tput rmso ) '{print B\$0N;}';
    OUTPUT=\$( git pull 2>&1; exit 0; );
    echo \"\${OUTPUT}\" | awk -v C=\"\$(
      { echo \"\${OUTPUT}\" | grep -q \"error\"; } && tput setaf 1 \
      || { [[ \$( echo \"\${OUTPUT}\" | wc -l ) -gt 1 ]] && tput setaf 3 \
           || echo \"\"; }
    )\" -v R=\"\$( tput sgr0 )\" '{ print C\"\t\"\$0R;}';"
