#!/bin/bash

cd $( dirname ${0} )
for FOLDER in $( find ${PWD} -maxdepth 1 -type d -not -path ${PWD} ); do
	if [[ -e "${FOLDER}/.git" ]]; then
		cd ${FOLDER} || continue
		STATUS=$( git status -s 2>&1 )
		[[ "${STATUS}" != '' ]] || continue
		pwd
		echo "${STATUS}" | awk '{ print "\t"$0; }'
	else
		continue
	fi
done
