#!/bin/bash

GIT_CMD="git -c color.status=always status -sb"
COLOR_CONDITIONAL='[[ $( echo "${OUTPUT}" | wc -l ) -gt 1 ]] || $( echo "${OUTPUT}" | grep -vq "\.\.\." ) || $( echo "${OUTPUT}" | grep -q "ahead" );'

source $( ! [[ $( readlink ${0} ) =~ ^/.* ]] && dirname ${0} )/$( [[ -n $( readlink ${0} ) ]] && dirname $( readlink ${0} ) )/generic-all
